name: Checkov Security Scan

on:
  push:
    branches:
      - master  # Adjust the branch if needed
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  checkov_scan:
    permissions:
      contents: read  # for actions/checkout to fetch code
      # security-events: write  # Commented out as it requires GitHub Advanced Security
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.1 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4.1.6 # v4.1.6

      - name: Checkov Scan
        id: checkov_scan
        uses: bridgecrewio/checkov-action@v12.2777.0 # v12.2777.0
        with:
          directory: '.'  # Root directory to scan (adjust if needed)
          output_format: 'cli'  # Output format (cli, json, junit_xml, sarif)
          # Add other Checkov configuration options here if necessary

      # Commented out the step that requires GitHub Advanced Security
      # - name: Upload SARIF file (optional)
      #   if: always()  # Always run this step, even if previous steps fail
      #   uses: github/codeql-action/upload-sarif@v3.25.8 # v3.25.8
      #   with:
      #     sarif_file: 'results.sarif'  # SARIF output file name (adjust if needed)