# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '16 0 * * 6'

permissions:
  contents: read

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.1 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4.1.6 # v4.1.6

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@914fa647b406c387000300b2f09bb28691be2b6d # v1.0.14
        
      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3.25.8 # v3.25.8
        with:
          sarif_file: devskim-results.sarif
