# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '32 10 * * 4'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read  # for pmd/pmd-github-action to determine modified files
      pull-requests: read  # for pmd/pmd-github-action to query PRs
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.1 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4.1.6 # v4.1.6
      - name: Set up JDK 11
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@9532c32f311fc353784e87f2ef2e730ee0a6b603
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/master/java'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3.25.8 # v3.25.8
        with:
          sarif_file: pmd-report.sarif
