name: Snyk Infrastructure as Code Scan

on:
  pull_request:
    branches: ['master']

permissions:
  contents: read

jobs:
  test-snyk:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      actions: read
      # security-events: write  # Commented out as it requires GitHub Advanced Security

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.1 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v4.1.6 # v4.1.6
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout the specific PR commit

      - name: Install Snyk
        run: curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk && chmod +x ./snyk && mv ./snyk /usr/local/bin/ && snyk -v

      - name: Snyk Authenticate
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}          

      # Commented out steps that require GitHub Advanced Security.          
      #- name: Snyk Scan
      #  id: snyk_scan
      #  uses: snyk/actions@b98d498629f1c368650224d6d212bf7dfa89e4bf # v0.4.0
      #  env:
      #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #  with:
      #    command: touch snyk.sarif && test --sarif-file-output=snyk.sarif 
      #    args: --all-projects # --severity-threshold=high 
          

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v3.25.8 # v3.25.8
      #   with:
      #     sarif_file: snyk.sarif
      #     checkout_path: '.' 
      #     token: ${{ secrets.GH_TOKEN }}

      - name: Print Snyk Scan Results
        if: always()  # Ensure this step runs even if previous steps fail.
        run: |
          snyk code test && snyk log4shell && snyk monitor